// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4sH6jHPrpR10M2z6uSVsTJK9orto3ANs',
    appId: '1:493449701177:web:df488a60213f93c899eae8',
    messagingSenderId: '493449701177',
    projectId: 'notesapp-cae95',
    authDomain: 'notesapp-cae95.firebaseapp.com',
    storageBucket: 'notesapp-cae95.firebasestorage.app',
    measurementId: 'G-E38P58T9ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAQQ0mO0CP2aumB3WDUty0oje_KzGl1WY',
    appId: '1:493449701177:android:fe7075b008d664c499eae8',
    messagingSenderId: '493449701177',
    projectId: 'notesapp-cae95',
    storageBucket: 'notesapp-cae95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYH18-r_3VPTMuzwYiJmLa9jHClj8yBxY',
    appId: '1:493449701177:ios:5a5843e9578c4d7399eae8',
    messagingSenderId: '493449701177',
    projectId: 'notesapp-cae95',
    storageBucket: 'notesapp-cae95.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );
}
